use std::path::Path;
use std::process::Command;

fn find_npm() -> (&'static str, Vec<&'static str>) {
    if cfg!(windows) {
        ("cmd", vec!["/c", "npm"])
    } else {
        ("npm", vec!["npm"])
    }
}

fn run_npm(dir: &str, args: &[&str]) {
    let (cmd, prefixes) = find_npm();
    let mut full_args = prefixes;
    full_args.extend(args.iter().copied());
    let status = Command::new(cmd)
        .current_dir(dir)
        .args(&full_args)
        .status()
        .expect("failed to run npm");
    assert!(status.success(), "npm {:?} failed in {}", args, dir);
}

fn copy_bridge() {
    let src = Path::new("js_bridge/dist/bridge.js");
    let dst = Path::new("src/js/scripts/bridge.js");
    std::fs::copy(src, dst).expect("failed to copy bridge.js to src/js/scripts/");
}

fn generate_host_install_script() {
    let content = r#"// Installs host API and globals into globalThis.
// Generated by build.rs from js_bridge.
if (globalThis.Bridge) {
  globalThis.Bridge.install();
}"#;
    std::fs::write("src/js/scripts/bridge_host_install.js", content)
        .expect("failed to write bridge_host_install.js");
}

fn generate_extract_script() {
    let content = r#"// Serializes declarations from global state.
// Generated by build.rs from js_bridge.
if (globalThis.Bridge && globalThis.Bridge.serializeDeclarations) {
  globalThis.Bridge.serializeDeclarations();
}"#;
    std::fs::write("src/js/scripts/bridge_extract.js", content)
        .expect("failed to write bridge_extract.js");
}

fn main() {
    println!("cargo:rerun-if-changed=js_bridge/src");
    println!("cargo:rerun-if-changed=js_bridge/package.json");
    println!("cargo:rerun-if-changed=build.rs");

    run_npm("js_bridge", &["install", "--no-audit", "--no-fund", "--no-progress"]);
    run_npm("js_bridge", &["run", "build"]);

    copy_bridge();
    generate_host_install_script();
    generate_extract_script();

    println!("cargo:warning=js_bridge built and bridge.js copied");
}
