use anyhow::{anyhow, Result};
use rquickjs::CatchResultExt;
use crate::js_runtime::{create_runtime, create_context};
use crate::js_host_api::{extract_declarations, Declarations};
use crate::js_host_api::script_emit;
use crate::js_host_api::script_rest;
use super::strip_export::strip_export_prefix;
use super::import_resolver::resolve_and_fetch;

fn create_rt_ctx() -> Result<(rquickjs::Runtime, rquickjs::Context)> {
    let rt = create_runtime()?;
    let ctx = create_context(&rt)?;
    Ok((rt, ctx))
}

fn get_host_api_script() -> String {
    [
        script_emit::host_api_script_part1(),
        script_emit::host_api_script_emit(),
        script_rest::host_api_script_rest().as_str(),
        script_rest::host_api_script_tail().as_str(),
    ].join("\n")
}

fn bundle_imports(source: &str) -> String {
    let mut result = String::new();
    let mut pending = vec![("index.js".to_string(), source.to_string())];
    let mut visited = std::collections::HashSet::new();
    visited.insert("index.js".to_string());
    while let Some((path, src)) = pending.pop() {
        let dir = path.rfind('/').map(|s| path[..s].to_string())
            .unwrap_or_default();
        for line in src.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("import ") {
                if let Some((target, content)) = resolve_and_fetch(&dir, trimmed) {
                    if visited.insert(target.clone()) {
                        pending.push((target, content));
                    }
                }
                continue;
            }
            result.push_str(&strip_export_prefix(line));
            result.push('\n');
        }
    }
    result
}

fn transform_source(source: &str) -> String {
    if source.contains("export default") {
        source.replace("export default", "var __module_default =")
    } else { source.to_string() }
}

fn eval_with_js_detail(
    ctx: &rquickjs::Context,
    label: &str,
    script: String,
) -> Result<()> {
    let res: Result<(), String> = ctx.with(|c| {
        match c.eval::<(), _>(script).catch(&c) {
            Ok(()) => Ok(()),
            Err(e) => {
                let value = match &e {
                    rquickjs::CaughtError::Exception(ex) => {
                        ex.clone().into_value()
                    }
                    rquickjs::CaughtError::Value(v) => v.clone(),
                    rquickjs::CaughtError::Error(_) => {
                        return Err(String::new())
                    }
                };
                let detail = match value.into_object() {
                    Some(obj) => {
                        let name: Result<String, rquickjs::Error> =
                            obj.get("name");
                        let message: Result<String, rquickjs::Error> =
                            obj.get("message");
                        match (name.ok(), message.ok()) {
                            (Some(n), Some(m)) if !m.is_empty() => {
                                format!("{}: {}", n, m)
                            }
                            (Some(n), _) if !n.is_empty() => n,
                            (_, Some(m)) => m,
                            _ => String::new(),
                        }
                    }
                    None => String::new(),
                };
                Err(detail)
            }
        }
    });
    match res {
        Ok(()) => Ok(()),
        Err(detail) => {
            if detail.is_empty() {
                Err(anyhow!(
                    "{}: Exception generated by QuickJS", label))
            } else {
                Err(anyhow!(
                    "{}: Exception generated by QuickJS ({})",
                    label, detail))
            }
        }
    }
}

pub fn extract_from_source(source: &str) -> Result<Declarations> {
    let (_rt, ctx) = create_rt_ctx()?;
    let bundled = bundle_imports(source);
    let transformed = transform_source(&bundled);
    let host_script = get_host_api_script();
    eval_with_js_detail(&ctx, "host API eval failed", host_script)?;
    eval_with_js_detail(&ctx, "module eval failed", transformed)?;
    let invoke_js = super::extract_invoke::get_invoke_js();
    eval_with_js_detail(&ctx, "invoke eval failed", invoke_js.to_string())?;
    extract_declarations(&ctx)
}
